backend:
  name: git-gateway
  branch: master
  accept_roles: #optional - accepts all users if left out
    - admin
    - editor

media_folder: static/img
public_folder: /img
publish_mode: editorial_workflow

collections:
  - name: "Pages"
    label: "Pages & Settings"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "home"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "home-page",
            }
          - {
              label: Background Image,
              name: backgroundImage,
              widget: image,
              required: false,
            }
          - { label: Title, name: title, widget: string }
          - { label: Headline, name: headline, widget: string }
          - { label: Sub-Headline, name: subHeadline, widget: string }
          - { label: Profile Image, name: profileImage, widget: image }
          - { label: Call To Action, name: cta, widget: string }
          - { label: Modal Submit Button, name: submit, widget: string }
          - {
              label: Sections,
              name: sections,
              widget: list,
              fields: [{ label: Body, name: body, widget: markdown }],
            }
      - file: "src/pages/thank-you.md"
        label: "Thank You Page"
        name: "thank-you"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "thank-you-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: Headline, name: headline, widget: string }
          - { label: Profile Image, name: profileImage, widget: image }
          - {
              label: Sections,
              name: sections,
              widget: list,
              fields: [{ label: Body, name: body, widget: markdown }],
            }
      - file: "src/pages/config.md"
        label: "Global Settings"
        name: "config"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "hidden-page",
            }
          - { label: Site Title, name: title, widget: "string" }
          - { label: Site Description, name: desc, widget: "string" }
          - { label: Heading Fonts, name: headingfonts, widget: fontpicker }
          - { label: Body Fonts, name: bodyfonts, widget: fontpicker }
